server: 
  port: 9096
spring: 
  application: 
    name: eureka-server
  profiles: service2
eureka: 
  instance: 
    hostname: eureka-server2
  client: 
    service-url: 
      defaultZone: http://localhost:9095/eureka
    # 自己不注册自己
    register-with-eureka: false