server: 
  port: 9095
spring: 
  application: 
    name: eureka-server
  profiles: service1
eureka: 
  instance: 
    hostname: eureka-server1
  client: 
    service-url: 
      defaultZone: http://localhost:9096/eureka
    # 自己不注册自己
    register-with-eureka: false
  # 失效剔除的时间设置为30秒，默认是60秒
  server: 
    eviction-interval-timer-in-ms: 30000